language: php
php:
  - '5.5'

before_install:
  - composer self-update
  - composer install

sudo: false

script: phpunit --configuration phpunit.xml

notifications:
  email:
    - ferid.movsumov@ideasoft.com.tr